package Vista;


public class GESTOR_VEHICULO extends javax.swing.JFrame {

    /**
     * Creates new form GESTOR_VEHICULO
     */
    public GESTOR_VEHICULO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BtnRegresarVehi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnInsertarV = new javax.swing.JButton();
        BtnBuscarV = new javax.swing.JButton();
        BtnModificarV = new javax.swing.JButton();
        BtnEliminarV = new javax.swing.JButton();
        BtnLimpiarVehi = new javax.swing.JButton();
        BtnTablaVehiculo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtTipoVehiculo = new javax.swing.JTextField();
        TxtColor = new javax.swing.JTextField();
        TxtModelo = new javax.swing.JTextField();
        TxtPlaca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtMarca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(141, 153, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 4, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FUNCIONARIO");

        BtnRegresarVehi.setBackground(new java.awt.Color(43, 45, 66));
        BtnRegresarVehi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnRegresarVehi.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresarVehi.setText("REGRESAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnRegresarVehi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(BtnRegresarVehi)
                .addGap(111, 111, 111))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 490));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GESTOR DE DATOS DEL TRANSITO DE BOGOTA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        BtnInsertarV.setBackground(new java.awt.Color(43, 45, 66));
        BtnInsertarV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnInsertarV.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsertarV.setText("INSERTAR");
        jPanel1.add(BtnInsertarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 95, 104, 45));

        BtnBuscarV.setBackground(new java.awt.Color(43, 45, 66));
        BtnBuscarV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscarV.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarV.setText("BUSCAR");
        jPanel1.add(BtnBuscarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 183, 104, 45));

        BtnModificarV.setBackground(new java.awt.Color(43, 45, 66));
        BtnModificarV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnModificarV.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarV.setText("MODIFICAR");
        jPanel1.add(BtnModificarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 268, 104, 45));

        BtnEliminarV.setBackground(new java.awt.Color(43, 45, 66));
        BtnEliminarV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEliminarV.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarV.setText("ELIMINAR");
        jPanel1.add(BtnEliminarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 347, 104, 45));

        BtnLimpiarVehi.setBackground(new java.awt.Color(43, 45, 66));
        BtnLimpiarVehi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnLimpiarVehi.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarVehi.setText("LIMPIAR");
        jPanel1.add(BtnLimpiarVehi, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 442, -1, -1));

        BtnTablaVehiculo.setBackground(new java.awt.Color(43, 45, 66));
        BtnTablaVehiculo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnTablaVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        BtnTablaVehiculo.setText("GENERAR TABLA VEHICULO");
        jPanel1.add(BtnTablaVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("VEHICULO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEDULA PROPIETARIO :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE PROPIETARIO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PLACA :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TIPO :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("COLOR :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("MARCA :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));
        jPanel1.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 320, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 320, -1));
        jPanel1.add(TxtTipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 320, -1));
        jPanel1.add(TxtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 320, -1));
        jPanel1.add(TxtModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 320, -1));
        jPanel1.add(TxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 320, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("MODELO :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        jPanel1.add(TxtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBuscarV;
    public javax.swing.JButton BtnEliminarV;
    public javax.swing.JButton BtnInsertarV;
    public javax.swing.JButton BtnLimpiarVehi;
    public javax.swing.JButton BtnModificarV;
    public javax.swing.JButton BtnRegresarVehi;
    public javax.swing.JButton BtnTablaVehiculo;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JTextField TxtColor;
    public javax.swing.JTextField TxtMarca;
    public javax.swing.JTextField TxtModelo;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtPlaca;
    public javax.swing.JTextField TxtTipoVehiculo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
