package Vista;


public class GESTOR_TECNOMECANICA extends javax.swing.JFrame {

    /**
     * Creates new form GESTOR_TECNOMECANICA
     */
    public GESTOR_TECNOMECANICA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BtnRegresarTec = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnInsertarTec = new javax.swing.JButton();
        BtnBuscarTec = new javax.swing.JButton();
        BtnModificarTec = new javax.swing.JButton();
        BtnEliminarTec = new javax.swing.JButton();
        BtnLimpiarTec = new javax.swing.JButton();
        BtnGenerarTablaTec = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtReftecno = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPlaca = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFechaVigencia = new javax.swing.JTextField();
        ComboCDA = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(141, 153, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 4, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FUNCIONARIO");

        BtnRegresarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnRegresarTec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnRegresarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresarTec.setText("REGRESAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnRegresarTec))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(BtnRegresarTec)
                .addGap(111, 111, 111))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 482));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GESTOR DE DATOS DEL TRANSITO DE BOGOTA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        BtnInsertarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnInsertarTec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnInsertarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsertarTec.setText("INSERTAR");
        BtnInsertarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(BtnInsertarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 95, 104, 45));

        BtnBuscarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnBuscarTec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarTec.setText("BUSCAR");
        BtnBuscarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 183, 104, 45));

        BtnModificarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnModificarTec.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnModificarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarTec.setText("MODIFICAR");
        BtnModificarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(BtnModificarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 268, 104, 45));

        BtnEliminarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnEliminarTec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEliminarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarTec.setText("ELIMINAR");
        BtnEliminarTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEliminarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 347, 104, 45));

        BtnLimpiarTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnLimpiarTec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnLimpiarTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarTec.setText("LIMPIAR");
        jPanel1.add(BtnLimpiarTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 442, -1, -1));

        BtnGenerarTablaTec.setBackground(new java.awt.Color(43, 45, 66));
        BtnGenerarTablaTec.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnGenerarTablaTec.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarTablaTec.setText("GENERAR TABLA REVISION");
        jPanel1.add(BtnGenerarTablaTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TECNOMECANICA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEDULA PROPIETARIO :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE PROPIETARIO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PLACA :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REF TECNO-M :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("FECHA VIGENCIA :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ESTADO :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        TxtReftecno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtReftecno, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, -1));

        TxtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 300, -1));

        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, -1));

        TxtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 300, -1));

        TxtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 300, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("CDA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        TxtFechaVigencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(TxtFechaVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 300, -1));

        ComboCDA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CDA ECCE LTDA", "DIAGNOSTIYA 170", "CDA INTECO S.A", "CDA AV SEXTA LTDA", "CDA PREVITAX S.A", "CDA SERVICOCHES", "CDA 183 S.A", " " }));
        ComboCDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimpiarTecActionPerformed(evt);
            }
        });
        jPanel1.add(ComboCDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLimpiarTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimpiarTecActionPerformed
     
    }//GEN-LAST:event_BtnLimpiarTecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBuscarTec;
    public javax.swing.JButton BtnEliminarTec;
    public javax.swing.JButton BtnGenerarTablaTec;
    public javax.swing.JButton BtnInsertarTec;
    public javax.swing.JButton BtnLimpiarTec;
    public javax.swing.JButton BtnModificarTec;
    public javax.swing.JButton BtnRegresarTec;
    public javax.swing.JComboBox<String> ComboCDA;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JTextField TxtEstado;
    public javax.swing.JTextField TxtFechaVigencia;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtPlaca;
    public javax.swing.JTextField TxtReftecno;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
