/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USER
 */
public class GESTOR_MATRICULA extends javax.swing.JFrame {

    /**
     * Creates new form GESTOR_MATRICULA
     */
    public GESTOR_MATRICULA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BtnRegresarMat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnInsertarMat = new javax.swing.JButton();
        BtnBuscarMat = new javax.swing.JButton();
        BtnModificarMat = new javax.swing.JButton();
        BtnEliminarMat = new javax.swing.JButton();
        BtnLimpiarMat = new javax.swing.JButton();
        BtnGenerarTablaMat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtIdTraspaso = new javax.swing.JTextField();
        TxtNombrePA = new javax.swing.JTextField();
        TxtNombrePN = new javax.swing.JTextField();
        TxtLugarT = new javax.swing.JTextField();
        TxtTipoMatricula = new javax.swing.JTextField();
        TxtFechaTras = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(141, 153, 174));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(217, 4, 41));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("FUNCIONARIO");

        BtnRegresarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnRegresarMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnRegresarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresarMat.setText("REGRESAR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnRegresarMat))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(BtnRegresarMat)
                .addGap(111, 111, 111))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 482));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GESTOR DE DATOS DEL TRANSITO DE BOGOTA ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        BtnInsertarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnInsertarMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnInsertarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsertarMat.setText("INSERTAR");
        jPanel5.add(BtnInsertarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 95, 104, 45));

        BtnBuscarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnBuscarMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarMat.setText("BUSCAR");
        jPanel5.add(BtnBuscarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 183, 104, 45));

        BtnModificarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnModificarMat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnModificarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarMat.setText("MODIFICAR");
        jPanel5.add(BtnModificarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 268, 104, 45));

        BtnEliminarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnEliminarMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEliminarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarMat.setText("ELIMINAR");
        jPanel5.add(BtnEliminarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 347, 104, 45));

        BtnLimpiarMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnLimpiarMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnLimpiarMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarMat.setText("LIMPIAR");
        jPanel5.add(BtnLimpiarMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 442, -1, -1));

        BtnGenerarTablaMat.setBackground(new java.awt.Color(43, 45, 66));
        BtnGenerarTablaMat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnGenerarTablaMat.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarTablaMat.setText("GENERAR TABLA MATRICULA");
        jPanel5.add(BtnGenerarTablaMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("TECNOMECANICA");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NOMBRE PROPIETARIO ANTIGUO :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE PROPIETARIO NUEVO :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("LUGAR TRASPASO :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID TRASPASO :");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("FECHA TRASPASO :");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TIPO DE MATRICULA :");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));
        jPanel5.add(TxtIdTraspaso, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, -1));
        jPanel5.add(TxtNombrePA, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 250, -1));
        jPanel5.add(TxtNombrePN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 250, -1));
        jPanel5.add(TxtLugarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, -1));
        jPanel5.add(TxtTipoMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 300, -1));
        jPanel5.add(TxtFechaTras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 300, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBuscarMat;
    public javax.swing.JButton BtnEliminarMat;
    public javax.swing.JButton BtnGenerarTablaMat;
    public javax.swing.JButton BtnInsertarMat;
    public javax.swing.JButton BtnLimpiarMat;
    public javax.swing.JButton BtnModificarMat;
    public javax.swing.JButton BtnRegresarMat;
    public javax.swing.JTextField TxtFechaTras;
    public javax.swing.JTextField TxtIdTraspaso;
    public javax.swing.JTextField TxtLugarT;
    public javax.swing.JTextField TxtNombrePA;
    public javax.swing.JTextField TxtNombrePN;
    public javax.swing.JTextField TxtTipoMatricula;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
