package Vista;

public class GESTOR_IMPUESTO extends javax.swing.JFrame {

    /**
     * Creates new form GESTOR_IMPUESTO
     */
    public GESTOR_IMPUESTO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BtnRegresarImp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnInsertarImp = new javax.swing.JButton();
        BtnBuscarImp = new javax.swing.JButton();
        BtnModificarImp = new javax.swing.JButton();
        BtnEliminarImp = new javax.swing.JButton();
        BtnLimpiarImp = new javax.swing.JButton();
        BtnGenerarImp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtRefImpuesto = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPlaca = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        TxtFechaLim = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFechaVig = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(141, 153, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 4, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FUNCIONARIO");

        BtnRegresarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnRegresarImp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnRegresarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresarImp.setText("REGRESAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnRegresarImp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(BtnRegresarImp)
                .addGap(111, 111, 111))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 482));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GESTOR DE DATOS DEL TRANSITO DE BOGOTA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        BtnInsertarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnInsertarImp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnInsertarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsertarImp.setText("INSERTAR");
        jPanel1.add(BtnInsertarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 95, 104, 45));

        BtnBuscarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnBuscarImp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarImp.setText("BUSCAR");
        jPanel1.add(BtnBuscarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 183, 104, 45));

        BtnModificarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnModificarImp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnModificarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarImp.setText("MODIFICAR");
        jPanel1.add(BtnModificarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 268, 104, 45));

        BtnEliminarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnEliminarImp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEliminarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarImp.setText("ELIMINAR");
        jPanel1.add(BtnEliminarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 347, 104, 45));

        BtnLimpiarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnLimpiarImp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnLimpiarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarImp.setText("LIMPIAR");
        jPanel1.add(BtnLimpiarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 442, -1, -1));

        BtnGenerarImp.setBackground(new java.awt.Color(43, 45, 66));
        BtnGenerarImp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnGenerarImp.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerarImp.setText("GENERAR TABLA IMPUESTO");
        jPanel1.add(BtnGenerarImp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("IMPUESTO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEDULA PROPIETARIO :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE PROPIETARIO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PLACA :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REF IMPUESTO :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("FECHA VIGENCIA :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ESTADO :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));
        jPanel1.add(TxtRefImpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, -1));
        jPanel1.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 300, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, -1));
        jPanel1.add(TxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 300, -1));
        jPanel1.add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 300, -1));
        jPanel1.add(TxtFechaLim, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("FECHA LIMITE :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        jPanel1.add(TxtFechaVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBuscarImp;
    public javax.swing.JButton BtnEliminarImp;
    public javax.swing.JButton BtnGenerarImp;
    public javax.swing.JButton BtnInsertarImp;
    public javax.swing.JButton BtnLimpiarImp;
    public javax.swing.JButton BtnModificarImp;
    public javax.swing.JButton BtnRegresarImp;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JTextField TxtEstado;
    public javax.swing.JTextField TxtFechaLim;
    public javax.swing.JTextField TxtFechaVig;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtPlaca;
    public javax.swing.JTextField TxtRefImpuesto;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
