package Vista;

public class GESTOR_COMPARENDOS extends javax.swing.JFrame {

    
    public GESTOR_COMPARENDOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        BtnRegresarComp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BtnInsertarComp = new javax.swing.JButton();
        BtnBuscarComp = new javax.swing.JButton();
        BtnModificarComp = new javax.swing.JButton();
        BtnEliminarComp = new javax.swing.JButton();
        BtnLimpiarComp = new javax.swing.JButton();
        BtnTablaComp = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtRefComparendo = new javax.swing.JTextField();
        TxtCedula = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtPlaca = new javax.swing.JTextField();
        TxtEstado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtFechaInf = new javax.swing.JTextField();
        ComboInfraccion = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        TxtFechaPa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(141, 153, 174));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(217, 4, 41));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("FUNCIONARIO");

        BtnRegresarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnRegresarComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnRegresarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegresarComp.setText("REGRESAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(BtnRegresarComp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 264, Short.MAX_VALUE)
                .addComponent(BtnRegresarComp)
                .addGap(111, 111, 111))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 482));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("GESTOR DE DATOS DEL TRANSITO DE BOGOTA ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 6, -1, -1));

        BtnInsertarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnInsertarComp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnInsertarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsertarComp.setText("INSERTAR");
        jPanel1.add(BtnInsertarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 95, 104, 45));

        BtnBuscarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnBuscarComp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnBuscarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnBuscarComp.setText("BUSCAR");
        jPanel1.add(BtnBuscarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 183, 104, 45));

        BtnModificarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnModificarComp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnModificarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnModificarComp.setText("MODIFICAR");
        jPanel1.add(BtnModificarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 268, 104, 45));

        BtnEliminarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnEliminarComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnEliminarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarComp.setText("ELIMINAR");
        jPanel1.add(BtnEliminarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 347, 104, 45));

        BtnLimpiarComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnLimpiarComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnLimpiarComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnLimpiarComp.setText("LIMPIAR");
        jPanel1.add(BtnLimpiarComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 442, -1, -1));

        BtnTablaComp.setBackground(new java.awt.Color(43, 45, 66));
        BtnTablaComp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnTablaComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnTablaComp.setText("GENERAR TABLA COMAPARENDO");
        jPanel1.add(BtnTablaComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("COMPARENDO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("CEDULA PROPIETARIO :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("NOMBRE PROPIETARIO :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PLACA :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("REF COMPARENDO :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("FECHA PAGO :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ESTADO :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));
        jPanel1.add(TxtRefComparendo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 300, -1));
        jPanel1.add(TxtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 300, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 300, -1));
        jPanel1.add(TxtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 300, -1));
        jPanel1.add(TxtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 300, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("TIPO DE INFRACCION :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));
        jPanel1.add(TxtFechaInf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 300, -1));

        ComboInfraccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C35 (Vencimiento o no haber pasado la tecnomecanica)", "D02 (Conducir sin SOAT)", "B01 (Conducir sin licencia)", "C14 (Conducir en pico y placa)", "D04 (Saltarse semaforo en rojo)", "C38 (Conducir utilziando celular)", "C06 (Conducir sin el cinturon)", "C02 (Estacionarse en lugares prohibidos)" }));
        jPanel1.add(ComboInfraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 300, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("FECHA INFRACCION :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));
        jPanel1.add(TxtFechaPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnBuscarComp;
    public javax.swing.JButton BtnEliminarComp;
    public javax.swing.JButton BtnInsertarComp;
    public javax.swing.JButton BtnLimpiarComp;
    public javax.swing.JButton BtnModificarComp;
    public javax.swing.JButton BtnRegresarComp;
    public javax.swing.JButton BtnTablaComp;
    public javax.swing.JComboBox<String> ComboInfraccion;
    public javax.swing.JTextField TxtCedula;
    public javax.swing.JTextField TxtEstado;
    public javax.swing.JTextField TxtFechaInf;
    public javax.swing.JTextField TxtFechaPa;
    public javax.swing.JTextField TxtNombre;
    public javax.swing.JTextField TxtPlaca;
    public javax.swing.JTextField TxtRefComparendo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
